version: "3.8"

services:
  php:
    build:
      context: docker/php
    volumes:
      - ./:/home/php-user/project
    tty: true
    ports:
      - "0.0.0.0:9000:9000"
    depends_on:
      - mysql
      - rabbit
    container_name: vault_php
  nginx:
    image: nginx:1.19
    volumes:
      - .:/home/php-user/project
      - ./docker/nginx/dev/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      - php
    container_name: vault_nginx
  mysql:
    image: mysql:8
    ports:
      - "0.0.0.0:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dev-password
    container_name: vault_mysql
  rabbit:
    image: rabbitmq:3.8-management-alpine
    ports:
      - "0.0.0.0:15672:15672"
    environment:
      RABBITMQ_VM_MEMORY_HIGH_WATERMARK: 256MiB
    container_name: vault_rabbit

